Feature/keep tags based on pattern (#1)
sethvargo/gcr-cleaner pull request #24
Opened 2021-03-27 05:32 UTC by luanphantiki

According to the idea from this [issue](https://github.com/sethvargo/gcr-cleaner/issues/16), I have added a tag filtering feature which helps us on filtering only tags with the declared prefix (tags begin with -tag-prefix definition).

**Notice** 

- This feature is just under a heavy construction, do not use it for your production until it's merged to master branch. 
- For every digest, I have only checked for the first tag in the tags array. My thought it's good enough for determining a digest can be removed or not.
- Feel free to correct me.

**Example**
Let's look at the example below

1. *What tags I have?*

    ```sh
    asia.gcr.io/foo/bar:staging-build-64
    asia.gcr.io/foo/bar:staging-build-63
    asia.gcr.io/foo/bar:staging-build-62
    asia.gcr.io/foo/bar:staging-build-61
    asia.gcr.io/foo/bar:staging-build-60
    asia.gcr.io/foo/bar:staging-build-59
    asia.gcr.io/foo/bar:staging-build-58
    asia.gcr.io/foo/bar:staging-build-55
    asia.gcr.io/foo/bar:staging-build-54
    asia.gcr.io/foo/bar:staging-build-52
    asia.gcr.io/foo/bar:master-build-38
    asia.gcr.io/foo/bar:master-build-37
    asia.gcr.io/foo/bar:master-build-36
    asia.gcr.io/foo/bar:master-build-35
    asia.gcr.io/foo/bar:master-build-34
    asia.gcr.io/foo/bar:master-build-33
    asia.gcr.io/foo/bar:master-build-32
    asia.gcr.io/foo/bar:master-build-31
    asia.gcr.io/foo/bar:master-build-30
    asia.gcr.io/foo/bar:master-build-29
    asia.gcr.io/foo/bar:dev-build-124
    asia.gcr.io/foo/bar:dev-build-123
    asia.gcr.io/foo/bar:dev-build-122
    asia.gcr.io/foo/bar:dev-build-121
    asia.gcr.io/foo/bar:dev-build-120
    asia.gcr.io/foo/bar:dev-build-119
    asia.gcr.io/foo/bar:dev-build-113
    asia.gcr.io/foo/bar:dev-build-112
    asia.gcr.io/foo/bar:dev-build-111
    asia.gcr.io/foo/bar:dev-build-110
    ```

1. *What tags will be removed if I run 2 commands as below ?*

    ```sh
    $ go run main.go -repo asia.gcr.io/foo/bar -keep 2 -allow-tagged -tag-prefix staging
    asia.gcr.io/foo/bar:staging-build-62
    asia.gcr.io/foo/bar:staging-build-61
    asia.gcr.io/foo/bar:staging-build-60
    asia.gcr.io/foo/bar:staging-build-59
    asia.gcr.io/foo/bar:staging-build-58
    asia.gcr.io/foo/bar:staging-build-55
    asia.gcr.io/foo/bar:staging-build-54
    asia.gcr.io/foo/bar:staging-build-52

    $ go run main.go -repo asia.gcr.io/foo/bar -keep 2 -allow-tagged -tag-prefix dev
    remove asia.gcr.io/foo/bar:dev-build-122
    remove asia.gcr.io/foo/bar:dev-build-121
    remove asia.gcr.io/foo/bar:dev-build-120
    remove asia.gcr.io/foo/bar:dev-build-119
    remove asia.gcr.io/foo/bar:dev-build-113
    remove asia.gcr.io/foo/bar:dev-build-112
    remove asia.gcr.io/foo/bar:dev-build-111
    remove asia.gcr.io/foo/bar:dev-build-110

    ```

2021-03-27 13:18 UTC, sethvargo commented
Hi @luanphantiki 

Thank you for the pull request. I think we should make this more generic. Instead of "prefix", we should support an arbitrary user-supplied pattern which we compile into a regex.

2021-03-27 15:03 UTC, luanphantiki commented
@sethvargo : 👍  agreed, it's more flexible than the current "prefix", let me change to this way.

2021-03-27 16:10 UTC, luanphantiki commented
@sethvargo : I have changed to fully regexp support, please have a look once you have time, thanks!

2021-03-28 19:49 UTC, sethvargo requested changes
Three small things:

1. Let's clarify the regular expression format
2. Wrap a returned error
3. Accept a pointer

I commented on the specific items inline too

2021-03-28 19:49 UTC, sethvargo commented on cmd/gcr-cleaner-cli/main.go
> +		return fmt.Errorf("failed to parse -tag-filter")
```suggestion
		return fmt.Errorf("failed to parse -tag-filter: %w", err)
```

2021-03-28 19:49 UTC, sethvargo commented on pkg/gcrcleaner/cleaner.go
> +func (c *Cleaner) shouldDelete(m gcrgoogle.ManifestInfo, since time.Time, allowTag bool, tagFilterRegexp regexp.Regexp) bool {
Let's accept the pointer here instead of dereferencing everywhere else.
```suggestion
func (c *Cleaner) shouldDelete(m gcrgoogle.ManifestInfo, since time.Time, allowTag bool, tagFilterRegexp *regexp.Regexp) bool {
```

2021-03-28 19:49 UTC, sethvargo commented on README.md
> +  is no filtering.
```suggestion
  is no filtering. The regular expression is parsed according to the [Go regexp package syntax](https://golang.org/pkg/regexp/syntax/).
```

2021-03-29 02:50 UTC, luanphantiki commented on pkg/gcrcleaner/cleaner.go
> +func (c *Cleaner) shouldDelete(m gcrgoogle.ManifestInfo, since time.Time, allowTag bool, tagFilterRegexp regexp.Regexp) bool {
Accepted on the latest commit.

2021-03-29 02:52 UTC, luanphantiki commented
@sethvargo requests accepted.

2021-03-29 08:45 UTC, manhcuongbk56 commented
amazing @luanphantiki . Thank you.

2021-03-29 14:04 UTC, sethvargo approved these changes

2021-03-29 14:04 UTC, merged

2021-03-29 14:08 UTC, sethvargo commented
Released in 0.4.0