Added the -recursive flag to load child repositories
sethvargo/gcr-cleaner pull request #37
Opened 2021-07-09 17:53 UTC by mmikitka

Say I have a repository tree structure like the following:
```
gcr.io/myproject/garden/garlic
gcr.io/myproject/garden/onions
gcr.io/myproject/bike/mountain
```

I want to run gcr-cleaner against all repositories without explicitly running the command against each one. This is currently not possible.

With the addition of the `-recursive` flag in this PR, I am now able to do:

Clean all repositories in gcr.io/myproject
```
gcr-cleaner-cli -repo gcr.io/myproject -recursive
```

Or, clean all garden repositories:
```
gcr-cleaner-cli -repo gcr.io/myproject/garden -recursive
```

2021-07-10 12:37 UTC, sethvargo requested changes

2021-07-10 12:37 UTC, sethvargo commented on pkg/gcrcleaner/cleaner.go
> +func (c *Cleaner) ListChildRepositories(rootRepository string) ([]string, error) {
This should accept a context as the first parameter and use that context when calling the other functions instead of context.TODO

2021-07-10 12:37 UTC, sethvargo commented on pkg/gcrcleaner/cleaner.go
> +	var matchPrefix string = rootRepo.RepositoryStr()
What is this for?

2021-07-10 12:37 UTC, sethvargo commented on pkg/gcrcleaner/cleaner.go
> +	for _, repo := range allRepos {
It'd be better to allocate `allRepos` down here instead of at the start of the function. You also have a rough idea of the max size it can be, so you can reduce allocs

2021-07-10 12:37 UTC, sethvargo commented on pkg/gcrcleaner/cleaner.go
> +	return childRepos, nil
Are these in any kind of order from the API? If not, we should sort them

2021-07-10 12:37 UTC, sethvargo commented on cmd/gcr-cleaner-cli/main.go
> +			return err
This should be a multierror and continue to clean the other repos

2021-07-12 15:17 UTC, mmikitka commented on pkg/gcrcleaner/cleaner.go
> +func (c *Cleaner) ListChildRepositories(rootRepository string) ([]string, error) {
Done

2021-07-12 15:17 UTC, mmikitka commented on pkg/gcrcleaner/cleaner.go
> +	var matchPrefix string = rootRepo.RepositoryStr()
Removed. Using the rootRepository input parameter instead

2021-07-12 15:18 UTC, mmikitka commented on pkg/gcrcleaner/cleaner.go
> +	for _, repo := range allRepos {
My Go skills are beginner level. I figured that I should not assume the number of repos returned by the function, so alternatives are appreciated.

2021-07-12 15:18 UTC, mmikitka commented on pkg/gcrcleaner/cleaner.go
> +	return childRepos, nil
Added a sort

2021-07-12 15:18 UTC, mmikitka commented on cmd/gcr-cleaner-cli/main.go
> +			return err
Done

2021-07-12 17:31 UTC, sethvargo commented on cmd/gcr-cleaner-cli/main.go
> +	var result error
```suggestion
	var result *multierror.Error
```

2021-07-12 17:31 UTC, sethvargo commented on cmd/gcr-cleaner-cli/main.go
> +	return result
```suggestion
	return result.ErrorOrNil()
```

2021-07-12 17:31 UTC, sethvargo commented on pkg/gcrcleaner/cleaner.go
> +	for _, repo := range allRepos {
I would suggest adding:

```go
childRepos := make([]string, 0, len(allRepos))
```

right before you loop. That will allocate a slice that is as big as possible, but it won't make any future allocations as you loop. Right now, you have a slice of size 0, so it could end up doubling (re-allocating) multiple times.

2021-07-12 20:42 UTC, mmikitka commented on pkg/gcrcleaner/cleaner.go
> +	for _, repo := range allRepos {
That makes sense, and I just applied this change.

2021-07-12 20:43 UTC, mmikitka commented on cmd/gcr-cleaner-cli/main.go
> +	var result error
Done

2021-07-12 20:43 UTC, mmikitka commented on cmd/gcr-cleaner-cli/main.go
> +	return result
Done

2021-07-12 21:13 UTC, sethvargo approved these changes

2021-07-12 21:14 UTC, merged